//! Native link flags for the runtime crate's linkable artifacts: the cdylib
//! (`libsaisei_runtime.so`, dlopen'd by the shim unit tests) and any binary
//! that depends on the rlib. SDL2 is located via pkg-config when it's installed
//! and by probing the standard library paths when it isn't — so pkg-config is
//! not itself a prerequisite, and a missing SDL2 fails with the install command
//! rather than a linker error. Plus the system libs the runtime calls directly.
//!
//! Also bakes the pre-game splash logo into a raw RGB24 blob for `sdl.rs` — the
//! decode and downscale happen once, here, so the display path links no image
//! decoder and the window pays no decode cost at startup.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

// Longest edge of the embedded logo. The splash draws through a texture of its
// own, sized well above the game's 320x200 (see SPLASH_MIN_EDGE in sdl.rs), so
// this is what caps the art's on-screen sharpness — it wants to be at least as
// large as the logo ever lands on a real window. The cost is linear: the blob is
// width * height * 3 bytes in the game binary.
const LOGO_MAX_EDGE: u32 = 1024;

fn bake_logo() {
    println!("cargo:rerun-if-changed=assets/saisei_logo.png");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let img = image::open("assets/saisei_logo.png")
        .expect("decode assets/saisei_logo.png")
        .resize(
            LOGO_MAX_EDGE,
            LOGO_MAX_EDGE,
            image::imageops::FilterType::Lanczos3,
        )
        .to_rgba8();
    let (w, h) = img.dimensions();

    // Flatten onto black: the art is black-backed, so the splash's letterbox bars
    // blend into it seamlessly and no alpha channel has to survive to run time.
    let mut rgb = Vec::with_capacity((w * h * 3) as usize);
    for px in img.pixels() {
        let a = px.0[3] as u32;
        for c in 0..3 {
            rgb.push((px.0[c] as u32 * a / 255) as u8);
        }
    }

    let blob = out_dir.join("logo.rgb");
    fs::write(&blob, &rgb).expect("write logo.rgb");
    fs::write(
        out_dir.join("logo.rs"),
        format!(
            "// Generated by build.rs from assets/saisei_logo.png.\n\
             pub(crate) const LOGO_W: usize = {w};\n\
             pub(crate) const LOGO_H: usize = {h};\n\
             pub(crate) static LOGO_RGB: &[u8; {len}] = include_bytes!({blob:?});\n",
            len = rgb.len(),
            blob = blob,
        ),
    )
    .expect("write logo.rs");
}

/// SDL2's link flags from pkg-config, if pkg-config is installed and knows about
/// it. Handles the unusual-prefix case (a hand-built SDL, a non-default brew
/// prefix) that path probing can't.
fn sdl2_from_pkg_config() -> Option<Vec<String>> {
    let out = Command::new("pkg-config")
        .args(["--libs", "sdl2"])
        .output()
        .ok()
        .filter(|o| o.status.success())?;
    let flags = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!flags.is_empty()).then(|| flags.split_whitespace().map(str::to_string).collect())
}

/// The places a package manager actually drops libSDL2, so that pkg-config is
/// not itself a prerequisite — `apt install libsdl2-dev` / `brew install sdl2`
/// is the whole install, and this finds what they put down.
///
/// We look for the *linker* name (libSDL2.so / libSDL2.dylib), which only the
/// dev package provides. A machine with just the runtime library
/// (libSDL2-2.0.so.0) can run an SDL program but cannot link one, and reporting
/// that as "found" would only defer the failure to a cryptic `-lSDL2` error.
fn sdl2_from_probe() -> Option<Vec<String>> {
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let dirs = [
        "/opt/homebrew/lib".to_string(),      // brew, Apple silicon
        "/usr/local/lib".to_string(),         // brew on Intel, /usr/local builds
        format!("/usr/lib/{arch}-linux-gnu"), // Debian/Ubuntu multiarch
        "/usr/lib64".to_string(),             // Fedora/RHEL
        "/usr/lib".to_string(),               // Arch and friends
    ];
    let names = ["libSDL2.so", "libSDL2.dylib"];
    dirs.iter()
        .find(|d| names.iter().any(|n| Path::new(d).join(n).exists()))
        .map(|d| vec![format!("-L{d}"), "-lSDL2".to_string()])
}

/// Everything Saisei needs from the system, in one message. A missing SDL2 must
/// not surface as `/usr/bin/ld: cannot find -lSDL2` — the first thing a new user
/// sees should be the command that fixes it.
fn sdl2_missing() -> ! {
    panic!(
        "\n\nSDL2 not found — Saisei opens its window with it.\n\n\
         Install it, then run `cargo build --release` again:\n\n  \
         Debian/Ubuntu   sudo apt install libsdl2-dev\n  \
         Fedora          sudo dnf install SDL2-devel\n  \
         Arch            sudo pacman -S sdl2\n  \
         macOS           brew install sdl2\n\n\
         (Already installed somewhere unusual? Then `pkg-config --libs sdl2` \
         has to find it.)\n"
    )
}

/// On macOS, target the running Mac's own OS version at link time. rustc's
/// default deployment target (11.0 on Apple Silicon) is older than what brew
/// built SDL2 for, so ld64 warns about the skew on every build — noise that
/// reads like a real problem ("was built for newer macOS version than being
/// linked"). The machine building Saisei is the machine playing on it (chunks
/// are JIT-compiled here at run time; nothing is distributed), so the host's
/// version is always the right one. An explicit MACOSX_DEPLOYMENT_TARGET still
/// wins: rustc already honors it everywhere, and this emits nothing.
fn macos_host_version_min() -> Option<String> {
    println!("cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET");
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos")
        || std::env::var("MACOSX_DEPLOYMENT_TARGET").is_ok()
    {
        return None;
    }
    let out = Command::new("sw_vers")
        .arg("-productVersion")
        .output()
        .ok()
        .filter(|o| o.status.success())?;
    let v = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!v.is_empty()).then(|| format!("-mmacosx-version-min={v}"))
}

fn main() {
    bake_logo();

    let flags = sdl2_from_pkg_config()
        .or_else(sdl2_from_probe)
        .unwrap_or_else(|| sdl2_missing());
    for tok in &flags {
        if let Some(dir) = tok.strip_prefix("-L") {
            println!("cargo:rustc-link-search=native={dir}");
        } else if let Some(lib) = tok.strip_prefix("-l") {
            println!("cargo:rustc-link-lib={lib}");
        }
    }
    if let Some(arg) = macos_host_version_min() {
        println!("cargo:rustc-cdylib-link-arg={arg}");
    }

    println!("cargo:rustc-link-lib=dl");
    println!("cargo:rustc-link-lib=pthread");
    println!("cargo:rustc-link-lib=m");
}
