//! Native link flags for the runtime crate's linkable artifacts: the cdylib
//! (`libsaisei_runtime.so`, dlopen'd by the shim unit tests) and any binary
//! that depends on the rlib. SDL2 comes from pkg-config (with a homebrew
//! fallback), plus the system libs the runtime calls directly.
//!
//! Also bakes the pre-game splash logo into a raw RGB24 blob for `sdl.rs` — the
//! decode and downscale happen once, here, so the display path links no image
//! decoder and the window pays no decode cost at startup.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

// Longest edge of the embedded logo. The splash draws through a texture of its
// own, sized well above the game's 320x200 (see SPLASH_MIN_EDGE in sdl.rs), so
// this is what caps the art's on-screen sharpness — it wants to be at least as
// large as the logo ever lands on a real window. The cost is linear: the blob is
// width * height * 3 bytes in the game binary.
const LOGO_MAX_EDGE: u32 = 1024;

fn bake_logo() {
    println!("cargo:rerun-if-changed=assets/saisei_logo.png");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let img = image::open("assets/saisei_logo.png")
        .expect("decode assets/saisei_logo.png")
        .resize(
            LOGO_MAX_EDGE,
            LOGO_MAX_EDGE,
            image::imageops::FilterType::Lanczos3,
        )
        .to_rgba8();
    let (w, h) = img.dimensions();

    // Flatten onto black: the art is black-backed, so the splash's letterbox bars
    // blend into it seamlessly and no alpha channel has to survive to run time.
    let mut rgb = Vec::with_capacity((w * h * 3) as usize);
    for px in img.pixels() {
        let a = px.0[3] as u32;
        for c in 0..3 {
            rgb.push((px.0[c] as u32 * a / 255) as u8);
        }
    }

    let blob = out_dir.join("logo.rgb");
    fs::write(&blob, &rgb).expect("write logo.rgb");
    fs::write(
        out_dir.join("logo.rs"),
        format!(
            "// Generated by build.rs from assets/saisei_logo.png.\n\
             pub(crate) const LOGO_W: usize = {w};\n\
             pub(crate) const LOGO_H: usize = {h};\n\
             pub(crate) static LOGO_RGB: &[u8; {len}] = include_bytes!({blob:?});\n",
            len = rgb.len(),
            blob = blob,
        ),
    )
    .expect("write logo.rs");
}

fn main() {
    bake_logo();

    let pkg = Command::new("pkg-config")
        .args(["--libs", "sdl2"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());

    match pkg {
        Some(flags) => {
            for tok in flags.split_whitespace() {
                if let Some(dir) = tok.strip_prefix("-L") {
                    println!("cargo:rustc-link-search=native={dir}");
                } else if let Some(lib) = tok.strip_prefix("-l") {
                    println!("cargo:rustc-link-lib={lib}");
                }
            }
        }
        None => {
            // Homebrew fallback (mirrors the launcher's resolve_sdl_flags).
            println!("cargo:rustc-link-search=native=/opt/homebrew/lib");
            println!("cargo:rustc-link-lib=SDL2");
        }
    }
    println!("cargo:rustc-link-lib=dl");
    println!("cargo:rustc-link-lib=pthread");
    println!("cargo:rustc-link-lib=m");
}
