#!/usr/bin/env python3
"""Generate the C configuration used by the runtime shim for a game.

The pipeline is JIT-only: no binary is decoded ahead of time, so the config
carries no per-binary dispatch table, no static call-target table, and no
entry symbol. The runtime loads the program image, takes the entry cs:ip from
the MZ header, and JIT-compiles every reached code segment on demand. The
config just names the program image and threads the game-specific machine
parameters (protected dispatch slots, init cs, PSP load segment) into the
runtime.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = "// Generated by generate_game_config.py; do not edit by hand.\n\n"


def _select_program(data: dict, program: str | None) -> dict:
    """Pick the program (sub-executable) to emit config for. Flat single-program
    configs (no "programs") are treated as one implicit program."""
    progs = data.get("programs")
    if not progs:
        return data
    want = program or data.get("default_program") or progs[0].get("name")
    prog = next((p for p in progs if p.get("name") == want), None)
    if prog is None:
        names = ", ".join(p.get("name", "?") for p in progs)
        raise ValueError(f"No program '{want}' in config. Available: {names}")
    return prog


def _as_int(value: int | str | None, default: int = 0) -> int:
    if value is None:
        return default
    if isinstance(value, str):
        return int(value, 0)
    return int(value)


def generate_config(config_path: Path, out_path: Path,
                    program: str | None = None) -> None:
    data = json.loads(config_path.read_text(encoding="utf-8"))
    game_name = data.get("name") or config_path.stem
    prog = _select_program(data, program)

    program_path = prog.get("program_path")
    if not program_path:
        raise ValueError(f"Config {config_path} must define program_path")

    init_cs = _as_int(prog.get("init_cs", data.get("init_cs", 0)))
    psp_seg = _as_int(prog.get("psp_seg", data.get("psp_seg", 0)))
    slots = prog.get("protected_slots", data.get("protected_slots", []))

    lines: list[str] = [HEADER, '#include "game_config.h"\n\n']

    # Protected dispatch slots are game-specific (a game that overruns its own
    # dispatch table); the runtime only allows writes to them from init_cs
    # during init. Absent -> no check.
    if slots:
        lines.append("static const ProtectedSlot game_protected_slots[] = {\n")
        for s in slots:
            lo = _as_int(s["lo"])
            hi = _as_int(s["hi"])
            lines.append(f"    {{0x{lo:05X}, 0x{hi:05X}, "
                         f"{json.dumps(s.get('name', ''))}}},\n")
        lines.append("};\n")
        lines.append("static const size_t game_protected_slot_count = "
                     "sizeof(game_protected_slots) / "
                     "sizeof(game_protected_slots[0]);\n\n")
    else:
        lines.append("static const ProtectedSlot *const "
                     "game_protected_slots = NULL;\n")
        lines.append("static const size_t game_protected_slot_count = 0;\n\n")

    lines.append("const GameConfig game_config = {\n")
    lines.append(f"    .name = {json.dumps(game_name)},\n")
    lines.append(f"    .program_path = {json.dumps(program_path)},\n")
    lines.append("    .entry = NULL,\n")
    lines.append("    .call_targets = NULL,\n")
    lines.append("    .call_target_count = 0,\n")
    lines.append("    .binary_dispatch = NULL,\n")
    lines.append("    .binary_dispatch_count = 0,\n")
    lines.append("    .protected_slots = game_protected_slots,\n")
    lines.append("    .protected_slot_count = game_protected_slot_count,\n")
    lines.append(f"    .init_cs = 0x{init_cs & 0xFFFF:04X},\n")
    lines.append(f"    .psp_seg = 0x{psp_seg & 0xFFFF:04X},\n")
    lines.append("};\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path, help="Path to game configuration JSON")
    parser.add_argument(
        "--out",
        type=Path,
        help="Output path for generated C file",
    )
    parser.add_argument(
        "--program",
        default=None,
        help="Program (sub-executable) to emit config for in a multi-program "
             "bundle (default: the bundle's default_program)",
    )
    args = parser.parse_args()

    out_path = args.out
    if out_path is None:
        out_path = Path("build") / f"{args.config.stem}_game_config.c"

    generate_config(args.config, out_path, program=args.program)


if __name__ == "__main__":
    main()
